export const FRONTEND_URL = process.env.VITE_FRONTEND_URL ?? ""
export const BACKEND_URL = process.env.VITE_BACKEND_URL ?? ""
export const RUNNER_URL = process.env.VITE_RUNNER_URL ?? ""
export const AUTH0_USERNAME = process?.env?.AUTH0_USERNAME ?? ""
export const AUTH0_PASSWORD = process?.env?.AUTH0_PASSWORD ?? ""
export const AUTH0_DOMAIN = process.env.VITE_AUTH0_DOMAIN ?? ""
export const AUTH0_AUDIENCE = process.env.VITE_AUTH0_AUDIENCE ?? ""
export const AUTH0_CLIENT_ID = process.env.VITE_AUTH0_CLIENT_ID ?? ""
